# Simple configure file for early-init program
[audiod]
cmd=/usr/sbin/audiod
pidfile=/run/early/audiod.pid
log=/run/audiod.txt
<end>

[audio-chime]
cmd=/usr/sbin/audio_chime
pidfile=/run/early/audio-chime.pid
wait=/dev/snd/pcmC0D0p
argv=/vendor/yesterday.wav
log=/run/audio-chime.txt
<end>

