# Simple configure file for early-init program
[init_early_test]
cmd=/early_services/system/bin/init_early_test
env=/early_services:/early_services/system:/early_services/system/lib64:/early_services/system/bin/bootstrap
pidfile=/early_services/run/early/init_early_test.pid
log=/early_services/run/init_early_test.txt
<end>

[esplash]
cmd=/early_services/vendor/bin/esplash
pidfile=/early_services/run/early/esplash.pid
log=/early_services/run/esplash.txt
<end>

[audio-nxp-auto]
cmd=/early_services/vendor/bin/audio-nxp-auto
env=/early_services:/early_services/system:/early_services/system/lib64:/early_services/system/bin
pidfile=/early_services/run/early/audio-nxp-auto.pid
log=/early_services/run/audio-nxp-auto.txt
<end>

[ais_server]
cmd=/early_services/vendor/bin/ais_server
env=/early_services:/early_services/system:/early_services/system/lib64:/early_services/system/lib
pidfile=/early_services/run/early/ais_server.pid
log=/early_services/run/ais_server.txt
<end>

[qcarcam_edrm_rvc]
cmd=/early_services/vendor/bin/qcarcam_edrm_rvc
env=/early_services:/early_services/system:/early_services/system/lib64:/early_services/system/lib
pidfile=/early_services/run/early/qcarcam_edrm_rvc.pid
log=/early_services/run/qcarcam_edrm_rvc.txt
group=system
<end>

[early_chime]
cmd=/early_services/vendor/bin/early_chime
argv=/early_services/etc/bike_bell.wav
env=/early_services:/early_services/system:/early_services/system/lib64:/early_services/system/bin/bootstrap
pidfile=/early_services/run/early/early_chime.pid
log=/early_services/run/early_chime.txt
group=system
<end>
