# Simple configure file for early-init program

[init_early_test]
cmd=/early_services/bin/init_early_test
pidfile=/early_services/run/early/init_early_test.pid
log=/early_services/run/init_early_test.txt
<end>
